### ISSUE TITLE
suggerimenti

### ISSUE THREAD

**Issue by FabioZTessitore** [christian99salerno/Stringa#1]
ho messo dei suggerimenti

**Comment by christian99salerno** [comment]
va bene e ho ricaricato i files stringa ma ancora errori molto probabilmente ho sbagliato qualcosa perfavore potete controllare di nuovo ?

**Comment by FabioZTessitore** [comment]
Appena posso. Se trovi qualche altro errore e lo correggi ricarica su github

Il 13 gen 2017 4:58 PM, "christian99salerno" <notifications@github.com> ha
scritto:

**Comment by christian99salerno** [comment]
va bene grazie mille avvisatemi se cotrollate i file così li aggiorno e vedo anche sul mio computer

**Comment by FabioZTessitore** [comment]
Devi aggiustare il file h (vedi i commenti)

Il main te lo avevo aggiustato io e lo hai riscritto come ti avevo detto di
non fare. Ma come è possibile?

Il 13 gen 2017 5:27 PM, "christian99salerno" <notifications@github.com> ha
scritto:

**Comment by christian99salerno** [comment]
Scusate sono stato uno stupido ho pensato che i vostri commenti dovevo scrivere cone codice invece era giusto come era scritto poiché lo avevate aggiustato voi scusate mille volte

**Comment by FrankieCaracciolo99** [comment]
Ciao  belli

**Comment by FabioZTessitore** [comment]
ho inviato dei suggerimenti

**Comment by FrankieCaracciolo99** [comment]
Grazie

Il 14/gen/2017 19:23, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by christian99salerno** [comment]
scusate prof. io ci provo a capire ma non ci riesco e non riesco a farlo funzione il soggetto è c nel carattere e ho messo c.set() ma niente e ho messo b.set() per la stringa e mi da sempre errore alla set e poi il delete per il vettore come si fa si mette delete s[] così ?

**Comment by FabioZTessitore** [comment]
ti ho corretto tutti gli errori. Ho lasciato in commento quello che avevi scritto così puoi confrontare.
(controlla tutti i file)

**Comment by christian99salerno** [comment]
Grazie di tutto

**Comment by FrankieCaracciolo99** [comment]
Buongiorno e buona domenica e forza Napoli

**Comment by FabioZTessitore** [comment]
nella set(), quando allochi memoria, devi mettere size+1

poi devi aggiustare indexOf() come abbiamo detto. (Aggiusta anche il ciclo, i va da 0 a size escluso)

**Comment by christian99salerno** [comment]
prof ho aggiustato andate a vedere

**Comment by FabioZTessitore** [comment]
Perché hai fatto indexOf come Iameo?

**Comment by christian99salerno** [comment]
perchè lo abbiamo fatto insieme Io Iameo e Vaccaro oggi in classe

**Comment by christian99salerno** [comment]
così è più bella come funzione di ricerca

**Comment by FabioZTessitore** [comment]
È meno utile però.
Nella classe metti la funzione che dice se il carattere è presente nella
stringa. Nel main fai le altre operazioni

Il 26 gen 2017 6:32 PM, "christian99salerno" <notifications@github.com> ha
scritto:

**Comment by christian99salerno** [comment]
se volete la metto come prima

**Comment by FabioZTessitore** [comment]
Prova a rimetterla come prima.
Poi fanne un'altra che accetta l'indice da dove cominciare a cercare nella
stringa

Il 26 gen 2017 6:35 PM, "christian99salerno" <notifications@github.com> ha
scritto:

**Comment by christian99salerno** [comment]
va bene ci provo

**Comment by christian99salerno** [comment]
Ho caricato i file se volete controllare non so se ho fatto come volevate voi

**Comment by FabioZTessitore** [comment]
Va bene
